---
abstract: 'validation of Danish FI numbers'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Exception: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-DK-FI
provides:
  Business::DK::FI:
    file: lib/Business/DK/FI.pm
    version: '0.07'
  Class::Business::DK::FI:
    file: lib/Class/Business/DK/FI.pm
    version: '0.07'
  Data::FormValidator::Constraints::Business::DK::FI:
    file: lib/Data/FormValidator/Constraints/Business/DK/FI.pm
    version: '0.07'
requires:
  Carp: '0'
  Class::InsideOut: '0'
  Exporter: '0'
  Params::Validate: '0'
  Readonly: '0'
  Try::Tiny: '0'
  perl: v5.5.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-FI
  homepage: http://logiclab.jira.com/wiki/display/BDKFI/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  projectChangelog: http://logiclab.jira.com/browse/BDKFI#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/BDKFI
  projectWiki: http://logiclab.jira.com/wiki/display/BDKFI/Home
  repository: https://github.com/jonasbn/bdkfi
version: '0.07'
