---
abstract: 'validation of Danish FI numbers'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Exception: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930001'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-DK-FI
provides:
  Business::DK::FI:
    file: lib/Business/DK/FI.pm
    version: 0.03
  Class::Business::DK::FI:
    file: lib/Class/Business/DK/FI.pm
    version: 0.01
  Data::FormValidator::Constraints::Business::DK::FI:
    file: lib/Data/FormValidator/Constraints/Business/DK/FI.pm
    version: 0.01
requires:
  Carp: 0
  Class::InsideOut: 0
  Exporter: 0
  Params::Validate: 0
  Readonly: 0
  Try::Tiny: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-FI
  homepage: http://logiclab.jira.com/wiki/display/BDKFI/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BDKFI
  x_ProjectChangelog: http://logiclab.jira.com/browse/BDKFI#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  x_ProjectSite: http://logicLAB.jira.com/browse/BDKFI
  x_ProjectWiki: http://logiclab.jira.com/wiki/display/BDKFI/Home
version: 0.03
